// Question.java: This entity class represents a question.
// It includes fields for ID, question text, and answer.
// Annotations define it as a JPA entity with autogenerated ID.



package com.education.ai.assessmentmarker.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Question {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String questionText;
    private String answer;

    // No-argument constructor
    public Question() {
    }

    // Parameterized constructor
    public Question(String questionText, String answer) {
        this.questionText = questionText;
        this.answer = answer;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQuestionText() {
        return questionText;
    }

    public void setQuestionText(String questionText) {
        this.questionText = questionText;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }
}
